# Default values for networkModule_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

routeOperator:
  image:
    repository: "dronev2/dronet-operator"
    pullPolicy: "IfNotPresent"
tunnelEndpointOperator:
  image:
    repository: "dronev2/dronet-operator"
    pullPolicy: "IfNotPresent"
