apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: tunnel-operator
  name: tunnel-operator
  namespace: dronet
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tunnel-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tunnel-operator
    spec:
      serviceAccountName: tunnel-operator-service-account
      containers:
        - image: liqo/tunnel-operator
          imagePullPolicy: Always
          name: tunnel-operator
          command: ["/usr/bin/liqonet"]
          resources: {}
          securityContext:
            privileged: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
status: {}