---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: advertisement-broadcaster
  name: advertisement-broadcaster
spec:
  replicas: 1
  selector:
    matchLabels:
      run: advertisement-broadcaster
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: advertisement-broadcaster
    spec:
      serviceAccountName: advertisement-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-node
      containers:
      - image: {{ .Values.broadcaster.image }}
        imagePullPolicy: {{ .Values.broadcaster.pullPolicy }}
        name: advertisement-operator
        command: ["/usr/bin/advertisement-broadcaster"]
        args:
          - "--cluster-id"
          - "$(CLUSTER_ID)"
          - "--gateway-ip"
          - "$(LOCAL_TUNNEL_PUBLIC_IP)"
          - "--gateway-private-ip"
          - "$(LOCAL_TUNNEL_PRIVATE_IP)"
        env:
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configmapName }}
                key: clusterID
          - name: LOCAL_TUNNEL_PUBLIC_IP
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configmapName }}
                key: gatewayIP
          - name: LOCAL_TUNNEL_PRIVATE_IP
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configmapName }}
                key: gatewayPrivateIP
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
