---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtual-kubelet
  namespace: default
  labels:
    k8s-app: virtual-kubelet

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: virtual-kubelet
  namespace: default
subjects:
  - kind: ServiceAccount
    name: virtual-kubelet
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: advertisement-operator
  name: advertisement-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: advertisement-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: advertisement-operator
    spec:
      serviceAccountName: virtual-kubelet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-node
      containers:
      - image: dronev2/advertisement-operator
        name: advertisement-operator
        command: ["/usr/bin/advertisement-operator"]
        args:
          - "--cluster-id"
          - "$(CLUSTER_ID)"
          - "--gateway-ip"
          - "$(LOCAL_TUNNEL_PUBLIC_IP)"
          - "--gateway-private-ip"
          - "$(LOCAL_TUNNEL_PRIVATE_IP)"
        env:
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: adv-operator-config
                key: clusterId
          - name: LOCAL_TUNNEL_PUBLIC_IP
            valueFrom:
              configMapKeyRef:
                name: adv-operator-config
                key: gatewayIP
          - name: LOCAL_TUNNEL_PRIVATE_IP
            valueFrom:
              configMapKeyRef:
                name: adv-operator-config
                key: gatewayPrivateIP
status: {}

