apiVersion: v1
kind: ConfigMap
metadata:
  name: adv-operator-config
  namespace: default
data:
  clusterId: # your cluster id
  gatewayIP: # your gateway IP address
  gatewayPrivateIP: # your gateway private IP address