# Default values for adv_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

advController:
  image:
    repository: "liqo/advertisement-operator"
    pullPolicy: "IfNotPresent"
  foreignClusterID: "clusterID"

broadcaster:
  image:
    repository: "liqo/advertisement-broadcaster"
    pullPolicy: "IfNotPresent"
