name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Run Tests
      run: go test ./...
    - name: Build docker container
      run: docker build -f build/virtual-kubelet/Dockerfile .
      if: github.ref != 'refs/heads/master'
    - name: Push image on repo
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: dronev2/virtual-kubelet
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: build/virtual-kubelet/Dockerfile 
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: github.ref == 'refs/heads/master'
    - name: Build docker container
      run: docker build -f build/advertisement-operator/Dockerfile .
      if: github.ref != 'refs/heads/master'
      - name: Push image on repo
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: dronev2/advertisement-operator
          username: ${{ secrets.DOCKER_USERNAME }}
          dockerfile: build/advertisement-operator/Dockerfile
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: Integration Test # default: 8398a7@action-slack
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
      if: always() && github.ref == 'refs/heads/master' # Pick up events even if the job fails or is canceled.
    - name: Push image on repo
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: dronev2/advertisement-operator
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: build/advertisement-operator/Dockerfile
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: github.ref == 'refs/heads/master'
